### ISSUE TITLE
Deploy Helm Chart

### ISSUE THREAD

**Issue by MarkAndersonTrocme** [aws/amazon-ec2-metadata-mock#157]
**Describe the feature**
It would be great to be able to install amazon-ec2-metatdata-mock from a chart repository to ease the install process.

**Is the feature request related to a problem?**
It is the standard to install hosted charts and not need to either download the release and unpack it or clone the repo to install it.

**Describe alternatives you've considered**
It can be cumbersome to install via the current approaches, and would make it much cleaner to have the chart hosted.

**Comment by brycahta** [comment]
Hello, yup that would definitely be useful. We will host the helm charts in the [eks-charts](https://github.com/aws/eks-charts) repo starting with the next release.
