### ISSUE TITLE
Passing null value in AEMM config parameter

### ISSUE THREAD

**Issue by richardgalestok** [aws/amazon-ec2-metadata-mock#187]
Hi i would like to ask whether is there any way how to pass null value in some of property by env variable such as `AEMM_METADATA_VALUES_IAM_SECURITY_CREDENTIALS_TOKEN: null` or maybe like `AEMM_METADATA_VALUES_IAM_SECURITY_CREDENTIALS: '{"Code":"Success"","LastUpdated":"2020-04-02T18:50:40Z","Type":"AWS-HMAC","AccessKeyId":"MY_ACCESS_KEY","SecretAccessKey":"MY_SECRET_KEY","Token":null,"Expiration":"2040-04-02T00:49:51Z"}"'`.
In my case it's still overriden by default values from the code, or in case of passing the whole json content i cannot obtain the specified values, they're empty.
Thank you a lot for any hint/workaround.

**Comment by brycahta** [comment]
I think we would need a change to the formatting logic to customize the output of `null`.  I was able to override the value via env; however, the `null` is in quotes which [does not match reality](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-identity-documents.html).

**Repro Steps**
* `export AEMM_METADATA_VALUES_IAM_SECURITY_CREDENTIALS_TOKEN=null`
* `./ec2-metadata-mock`
* `curl localhost:1338/latest/meta-data/iam/security-credentials/baskinc-role` :

```
curl localhost:1338/latest/meta-data/iam/security-credentials/baskinc-role
{
	"Code": "Success",
	"LastUpdated": "2020-04-02T18:50:40Z",
	"Type": "AWS-HMAC",
	"AccessKeyId": "12345678901",
	"SecretAccessKey": "v/12345678901",
	"Token": "null", --> real IMDS shows no quotes
	"Expiration": "2020-04-02T00:49:51Z"
}%
```

**Comment by richardgalestok** [comment]
Hi, any chance to figure this issue out or possible workaround?

**Comment by brycahta** [comment]
@richardgalestok per my explanation, this would require a code change. I'll remove `stale` because we should align *null* output with IMDS; however, I'm not sure if we'll be able to get to it this year.
