### ISSUE TITLE
[bug] cannot add a new tag using config overrides

### ISSUE THREAD

**Issue by skyleguy** [aws/amazon-ec2-metadata-mock#198]
**Describe the bug**
A concise description of what the bug is.

I am trying to add a new tag by using the config override option as follows:

ec2-overrides.json

```
{
  "paths": {
    "tags-instance-supercooltest": "/latest/meta-data/tags/instance/supercooltest"
  },
  "metadata": {
    "values": {
      "tags-instance-supercooltest": "supercoolvalue"
    }
  }
}
```

However when i hit `http://localhost:1338/latest/meta-data/tags/instance` i still only see:

Name
Test

which is the default behavior

**Steps to reproduce**
create a .json file as specified above and use that file with the -c flag:

`ec2-metadata-mock -c /path/to/file/ec2-overrides.json`

then hit the endpoint that returns all tags: `http://localhost:1338/latest/meta-data/tags/instance`

**Expected outcome**
A concise description of what you expected to happen.

I would expect a new tag to be added to the mock data when hitting /latest/meta-data/tags/instance so the response would look like:

Name
Test
Supercooltest

and then hitting /latest/meta-data/tags/instance/Supercooltest I would receive `supercoolvalue` as the response

I know that my override file is being used as i am able to change the ami-id using my .json file

**Environment**

* AEMM Version: 1.11.2
* OS/Arch: macOS Ventura 13.2.1 (M1 Chip)
* Installation method: Brew

**Comment by rvodden** [comment]
I am also seeing this issue,,,

**Comment by joaopedrocg27** [comment]
same issue
