### ISSUE TITLE
Can't Run Binary: command not found

### ISSUE THREAD

**Issue by jkim-codecademy** [aws/amazon-ec2-metadata-mock#8]
OS + Kernel: 5.6.8-1-MANJARO

What I Did
```
curl -Lo amazon-ec2-metadata-mock https://github.com/aws/amazon-ec2-metadata-mock/releases/download/latest/amazon-ec2-metadata-mock
```
```
sudo chmod +x amazon-ec2-metadata-mock
```

```
 ./amazon-ec2-metadata-mock
./amazon-ec2-metadata-mock: line 1: Not: command not found
```

Build directly from source worked

**Comment by pdk27** [comment]
Hello, 

amazon-ec2-metadata-mock is yet to be launched. We are working on setting up our pipelines for CI/CD, after which the project will be ready for launch and you should find the first release in https://github.com/aws/amazon-ec2-metadata-mock/releases :)  
Post launch, other installation methods like Helm, kube-ctl will also be supported.

In the meantime, feel free to build from source and try it out.
