### ISSUE TITLE
Support for /meta-data/instance-life-cycle

### ISSUE THREAD

**Issue by petrukngantuk** [aws/amazon-ec2-metadata-mock#81]
is there a plan to support for /meta-data/instance-life-cycle?

**Comment by brycahta** [comment]
hey @petrukngantuk, I confirmed this is definitely a valid path on my ec2 instance, but not seeing it in the [documentation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-categories.html). Out of curiosity, how did you come across this path?

I'll do some research on my end to see if this is a one-off addition or if it's one of many paths that need to be added so we can batch appropriately. From there, I can provide a better answer as to if/when we can support `/meta-data/instance-life-cycle`


For future reference:

```
[ec2-user@ip-172-31-34-43 ~]$ curl http://169.254.169.254/latest/meta-data/instance-life-cycle
on-demand[ec2-user@ip-172-31-34-43 ~]$
[ec2-user@ip-172-31-34-43 ~]$ curl http://169.254.169.254/latest/meta-data/instance-life-cycle/on-demand
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>404 - Not Found</title>
 </head>
 <body>
  <h1>404 - Not Found</h1>
 </body>
</html>
```

**Comment by petrukngantuk** [comment]
Well when I use mixed asg on-demand n spot instance in our eks cluster

When instance type on-demand its return normal/on-demand,iirc. But when we have spot instance it's return spot. When we curl to /meta-data/instance-life-cycle
